name: Git Actions Demo
on: [push]
jobs:
 Explore-GitHub-Actions:
   runs-on: windows-latest
   steps:
     - uses: actions/checkout@v2
     - run: echo "The job was automatically triggered by a ${{ github.event_name }} event"
     - run: unit_testing\compare.py
     - run: unit_testing\test_compare_unittest.py
     - run: selenium_python_tasks\task1.py
     - run: selenium_python_tasks\task2.py